#!/bin/sh
# autoscript
# Creates a new shell file, makes it executable, and opens it in a text editor

print_usage() {
	printf 'usage: ./autoscript [LANGUAGE] FILE\n' >&2
}

language='sh'

case "$#" in
	1)
		filename="$1"
		;;
	2)
		language="$1"
		filename="$2"
		;;
	*)
		print_usage
		exit 1
		;;
esac

if [ -e "$filename" ]
then
	printf 'autoscript: %s - File already exists.\n' "$filename" >&2
	exit 1
fi

case $language in
	sh|shell)
		cat <<- 'EOF' > "$filename"
		#!/bin/sh
		EOF
		;;
	bash)
		cat <<- 'EOF' > "$filename"
		#!/usr/bin/env bash
		EOF
		;;
	py|python)
		cat <<- 'EOF' > "$filename"
		#!/usr/bin/env python3

		def main():
		    ...

		if __name__ == "__main__":
		    main()
		EOF
		;;
	rb|ruby)
		cat <<- 'EOF' > "$filename"
		#!/usr/bin/env ruby

		def main
		  # ...
		end

		if $PROGRAM_NAME == __FILE__
		  main
		end
		EOF
		;;
esac

chmod u+x "$filename"
$EDITOR "$filename"
