#!/bin/sh
# autoscript
# Creates a new shell file, makes it executable, and opens it in a text editor

[ -f $1 ] && {
	printf "%s already exists\n" "$1"
	exit 1
}

echo '#!/bin/sh' > $1
chmod +x $1
$EDITOR $1
