#!/bin/sh
# cheat
# Curl cheat.sh command-line cheatsheets. The cheat.sh repository can be found
# at https://github.com/chubin/cheat.sh

search_query=$(printf "%s" "$*" | sed "s/ /+/g")
curl "cheat.sh/$search_query"
