#!/bin/sh
# phpdestr
# Turns obnoxiously concatenated php strings back into normal text

# Removes succeeding quote + concat operators, preceding quotes
# and empty lines
sed 's/\s*"\s*[\.\;]\s*$//g;s/^\s*"\s*//g;/^$/d' ${1:-/dev/stdin}
